language: csharp
dist: trusty
mono:
  - latest
git:
  depth: 300
  
script:
  - bash travis-ci/autoversion.sh QuadTrees
  - export EnableNuGetPackageRestore=false
  - cert-sync /etc/ssl/certs/ca-certificates.crt
  - xbuild CI.proj
  - sudo nunit-console -framework=4.0 ./QuadTrees.Tests/bin/Debug/QuadTrees.Tests.dll -exclude Integration,NotWorkingOnMono
  - travis_retry bash travis-ci/nuget-upload.sh